### ISSUE TITLE
Go to definition, not just declaration?

### ISSUE THREAD

**Issue by nelhage** [emacs-lsp/lsp-clangd#10]
`M-.` (`xref-find-definitions`) seems to take me to the header file that declares a method. Is there a way to jump to the source file that also defines its implementation?

**Comment by tee3** [comment]
I'll try to do look into this in next few days.  You're kind of looking for a "jump-to-implementation" functionality and I'm not sure if that is accounted for in `xref`.

However, `lsp-clangd` just configures `lsp-mode` and does not have control over what either `lsp-mode` or `clangd` actually do, so it cannot be fixed in `lsp-clangd`.  This is probably a question for Emacs itself (`xref`), `lsp-mode`, or `clangd`.

**Comment by velkyel** [comment]
what version of clangd are you running?  My ubuntu package installation (tried clang-tools-7 and clang-tools-6.0) say "Capability not supported by the language server: "implementationProvider"" on lsp-goto-implementation.

**Comment by MaskRay** [comment]
`textDocument/implementation` has not been implemented
https://github.com/llvm-mirror/clang-tools-extra/blob/master/clangd/ProtocolHandlers.h#L53

If you care much about cross references (especially `textDocument/references`), you may consider using https://github.com/MaskRay/ccls/wiki/Emacs

**Comment by velkyel** [comment]
@MaskRay so, then it makes clangd barely usable.  I'll try ccls, thank you.

**Comment by innerout** [comment]
clangd's most powerful feature is auto-completion it excels over ccls and cquery in speed and accuracy but lacks in features that the other 2 clients support like cross references. @velkyel

**Comment by tee3** [comment]
Support for cross-references is available in `clangd` from the latest head of `clang-tools-extra`, so I'm closing this.
