### ISSUE TITLE
[feature] Create customization for root directory locator

### ISSUE THREAD

**Issue by jefftrull** [emacs-lsp/lsp-clangd#11]
I am unable to use lsp-clangd as-is because my `compile_commands.json` normally lives in an out-of-source build directory underneath the root directory, and `lsp-make-traverser` only looks _up_ the directory tree.

Please add a customization so I can supply my own locator function.

**Comment by jefftrull** [comment]
I state this problem inaccurately, sorry. The problem in this case is that `compile_commands.json` is not in my root directory, and so it cannot be used to find it. I would like to provide my own function to find the root directory (I use `projectile-project-root`)

**Comment by tee3** [comment]
How does this relate to #11?  Do you want to determine the root separately from the ‘compile_commands.json’?  That makes sense to me.  You would like to write your own function to determine the root?  Would the best default be using the standard ‘project’ system or looking for compile commands?  I’ll think about it and see what I come up with.  Thanks for your feedback!

**Comment by MaskRay** [comment]
In emacs-ccls, I use a simple approach

* locate .ccls-root
* if it does not exist, use projectile-project-root

**Comment by jefftrull** [comment]
Yes, my primary goal is for compile_commands.json to not be in the root :)

Here's my client definition:
```Lisp
  (lsp-define-stdio-client
   lsp-clangd-c++
   "cpp"
   'projectile-project-root   ;; let Projectile supply the root directory
   nil                        ;; command line calculated at runtime below
   :ignore-regexps
   '("^Error -[0-9]+: .+$")   ;; ?? - was in lsp-clangd
   :command-fn                ;; ensure clangd gets CDB
   (lambda ()
     ;; clangd executable
     (list "/path/to/llvm/build/bin/clangd"
           (concat "--compile-commands-dir="
                   (projectile-project-root)
                   "build"))))

```
I would be happy to use lsp-clangd if it could accommodate this usage.

**Comment by tee3** [comment]
It looks like `lsp-mode` is going to subsume all the individual language server modes described in https://github.com/emacs-lsp/lsp-mode/issues/479. I'll be closing this issue once that happens.

**Comment by tee3** [comment]
Please let me know if you are able to customize this with the new implementation of `lsp-mode`.  `lsp-clangd` is now a client within `lsp.el` and provides some better control.  If not, please file an issue there and we can work to get it resolved there.  Thanks!

**Comment by jefftrull** [comment]
Well, I gave it a try... but there doesn't seem to be any "clangd" client defined in the version on MELPA (20181208.1953). I also couldn't find any information about how to configure a specific client to run in the new documentation :(

**Comment by tee3** [comment]
Thanks for trying it out and being patient with the state of flux of the `clangd` support in `lsp-mode.` :)

Support for `clangd` was added this morning, so it may not have propagated yet when you tried it.  I just checked and it is now on the MELPA (non-stable) version.

Also, since there are several competing C++ language servers, there is no C++ language server registered by default.  However, there is a function included with `lsp-mode` (`lsp-clients-register-clangd`) that should register the `clangd` language server when called.  I believe the idea is to call that once `lsp-mode` is configured if you use `clangd` as your language server.


Note that I am using `eglot` more than `lsp-mode` currently, so I have not spent a lot of time setting up `lsp-mode` lately.  Please let me know if the above does not work and I will try to get it cleaned up.  If it does work, we can work to get it documented in `lsp-mode` so future users will know how to complete the configuration.

I hope that the `lsp-mode` maintainers will come up with a mechanism choose from several language servers for a mode or the C++ language server landscape will converge on a single server with all the desired features.  I'd like to see it based on what language server is found on the executable path or otherwise properly configured, but I am not a developer, just a user.

I used something like the following in my `.emacs` to configure 'clangd` for `lsp-mode`.  There are probably better ways to require `lsp-clients` in `use-package`, but I have not worked through that yet.  Having said that, it does seem to work properly.

```
(use-package lsp-mode
  :ensure t
  :pin melpa
  :init
  (require 'lsp-clients)
  (when (equal system-type 'darwin)
      (setq lsp-clients-clangd-executable "/usr/local/opt/llvm/bin/clangd"))
  :config
  (lsp-clients-register-clangd))
```

**Comment by tee3** [comment]
Note that you also have to run `M-x lsp` after visiting a file to enable `lsp` in a buffer.

This can also be automatically by adding a hook to each programming mode with which you want to enable `lsp`.  In the `use-package` example above, this can be done by the `:hook` keyword to the `use-package` form.

```
:hook
(c++-mode . lsp)
```

I don't do this yet as I'm hoping for something better than a hook for each type of file with which I want to use `lsp-mode`.

**Comment by jefftrull** [comment]
Thanks for the tips. I wish this had been in the lsp-mode docs :)

At this point I have lsp running using my selected clang executable but there are a lot of mysterious errors I'll need to diagnose - it's at this time a bit of a downgrade from the previous situation. Regardless I can file bugs on lsp-mode itself now. Thanks for the help!

**Comment by yyoncho** [comment]
@jefftrull 

> At this point I have lsp running using my selected clang executable but there are a lot of mysterious errors I'll need to diagnose - it's at this time a bit of a downgrade from the previous situation.

Would you open an issue in lsp-mode?

**Comment by MaskRay** [comment]
I think this can probably be used:
```elisp
(use-package lsp-mode
  :commands lsp
  :config
  (require 'lsp-clients)
  (lsp-clients-register-clangd))
```

**Comment by tee3** [comment]
@MaskRay That is a nice, concise version of what I presented above (without the `:ensure` for installing the package), thanks!

**Comment by jefftrull** [comment]
> Would you open an issue in lsp-mode?

Yep, I will do some debugging first though.
