### ISSUE TITLE
[bug] lsp-clangd relies on a now obsolete no-op'd macro

### ISSUE THREAD

**Issue by josteink** [emacs-lsp/lsp-clangd#17]
lsp-clangd uses the lsp-mode macro `lsp-define-stdio-client`.

Looking at current lsp-mode implementation it now looks like this:

````emacs-lisp
(defmacro lsp-define-stdio-client (&rest _rest)
  "No op - only for backward compatibility.")
````

This seemingly reduces `lsp-clangd` itself to a no-op.

Or am I doing something horribly wrong?

**Comment by yyoncho** [comment]
You have 2 options:

1. Delete lsp-clangd.elc (it is located in your emacs folder) to force byte compilation which will make lsp-clangd work as before or

2. Migrate to lsp.el . In order to do that you have to include the following PR: https://github.com/emacs-lsp/lsp-mode/pull/511 and follow the instructions from https://github.com/emacs-lsp/lsp-mode/blob/master/README-NEXT.md

**Comment by tee3** [comment]
This repository is now officially deprecated and archived.
